### ISSUE TITLE
Create a vision and mission

### ISSUE THREAD

**Issue by bramvoets** [ml4rookies/ml4rookies.github.io#5]
In order to foster participation, we should have a clear description of vision and mission.

**Comment by almo** [comment]
Introduced a proposal for discussion in our next meeting.

**Comment by SamuelMarks** [comment]
I'll have a crack at that first draft:

**Mission**
Machine Learning texts and interactive course, that's actually kept up-to-date. Written by the community, multilingual, and open-source.

**Vision**
Reducing the barrier to entry for understanding and implementing machine-learning.

**Comment by almo** [comment]
Thank you Samuel; you can also check my own proposal in [the agenda](https://github.com/ml4rookies/Course/wiki/June-16th%2C-2020-Meeting-Notes) for the meeting next week.
Let's discuss then.

**Comment by almo** [comment]
After discussion during the meeting, we need to update the documentation with the new [Vision and Mission](https://github.com/ml4rookies/Course/wiki/June-16th%2C-2020-Meeting-Notes#Discussion-Topics)

**Comment by almo** [comment]
Obsolete.
