### ISSUE TITLE
"Tooling" content not appearing in landing page

### ISSUE THREAD

**Issue by rafaelsf80** [ml4rookies/ml4rookies.github.io#9]
Can not see "Tooling" content in the latest update of the landing page.
Note that content was in a separate branch (02-Tooling)

**Comment by almo** [comment]
Thank you @rafaelsf80 for the heads up!

Please take a look at the structure followed at 01.Fundamentals:

  - README.md containing the whole content.
  - A images containing all the images.

and follow the same structure for the tooling section. We will discuss in our next meeting few more things about content and deployment.

Let me know when ready.

Thanks

**Comment by rafaelsf80** [comment]
Already updated according to the guidelines in main branch.

**Comment by almo** [comment]
Obsolete.
